################ Social ##################
[[social]]
title = "twitter"
icon = "fa-brands fa-x-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/adamwarski"

[[social]]
title = "linkedin"
icon = "fa-brands fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/in/adamwarski/"

[[social]]
title = "github"
icon = "fa-brands fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/adamw"

[[social]]
title = "mastodon"
icon = "fa-brands fa-mastodon" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://softwaremill.social/@adamwarski"

[[social]]
title = "bluesky"
icon = "fa-brands fa-bluesky" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://bsky.app/profile/warski.org"
